{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP5F4otYAZJqgLRSj9+MLtq",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sanchigupta287/Goal-Tracker/blob/main/goal%20tracker.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DXBml7Lj208u",
        "outputId": "ba3c4570-e7c7-4169-9966-1caab9372716"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "==============================\n",
            "   GOAL & HABIT TRACKER CLI   \n",
            "==============================\n",
            "1. Add New Goal\n",
            "2. View All Goals\n",
            "3. Update Goal Progress\n",
            "4. View Progress Analytics\n",
            "5. Exit\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "\n",
        "DATA_FILE = \"goals.txt\"\n",
        "\n",
        "def load_goals():\n",
        "    \"\"\"Reads saved goals from goals.txt line by line.\"\"\"\n",
        "    goals = []\n",
        "    if not os.path.exists(DATA_FILE):\n",
        "        return goals\n",
        "\n",
        "    with open(DATA_FILE, \"r\") as file:\n",
        "        for line in file:\n",
        "            line = line.strip()\n",
        "            if line:\n",
        "                parts = line.split(\",\")\n",
        "                if len(parts) == 5:\n",
        "                    goal = {\n",
        "                        \"id\": int(parts[0]),\n",
        "                        \"title\": parts[1],\n",
        "                        \"category\": parts[2],\n",
        "                        \"progress\": int(parts[3]),\n",
        "                        \"status\": parts[4]\n",
        "                    }\n",
        "                    goals.append(goal)\n",
        "    return goals\n",
        "\n",
        "def save_goals(goals):\n",
        "    \"\"\"Saves updated goals to goals.txt.\"\"\"\n",
        "    with open(DATA_FILE, \"w\") as file:\n",
        "        for g in goals:\n",
        "            file.write(f\"{g['id']},{g['title']},{g['category']},{g['progress']},{g['status']}\\n\")\n",
        "\n",
        "def add_goal(goals):\n",
        "    \"\"\"Module 1: Adds a new goal.\"\"\"\n",
        "    print(\"\\n--- ADD NEW GOAL ---\")\n",
        "    title = input(\"Enter Goal Title: \").strip()\n",
        "    category = input(\"Enter Category (e.g., Academic, Fitness): \").strip()\n",
        "\n",
        "    goal_id = len(goals) + 1\n",
        "    new_goal = {\n",
        "        \"id\": goal_id,\n",
        "        \"title\": title,\n",
        "        \"category\": category,\n",
        "        \"progress\": 0,\n",
        "        \"status\": \"In Progress\"\n",
        "    }\n",
        "    goals.append(new_goal)\n",
        "    save_goals(goals)\n",
        "    print(f\"✅ Goal '{title}' added successfully!\")\n",
        "\n",
        "def view_goals(goals):\n",
        "    \"\"\"Module 2: Displays all tracked goals.\"\"\"\n",
        "    print(\"\\n--- YOUR GOALS ---\")\n",
        "    if not goals:\n",
        "        print(\"No goals found. Add one first!\")\n",
        "        return\n",
        "\n",
        "    for g in goals:\n",
        "        print(f\"[{g['id']}] {g['title']} | Category: {g['category']} | Progress: {g['progress']}% | Status: {g['status']}\")\n",
        "\n",
        "def update_progress(goals):\n",
        "    \"\"\"Module 3: Updates goal progress percentage.\"\"\"\n",
        "    view_goals(goals)\n",
        "    if not goals:\n",
        "        return\n",
        "\n",
        "    try:\n",
        "        goal_id = int(input(\"\\nEnter Goal ID to update: \"))\n",
        "        selected = next((g for g in goals if g[\"id\"] == goal_id), None)\n",
        "\n",
        "        if selected:\n",
        "            new_prog = int(input(\"Enter new progress percentage (0-100): \"))\n",
        "            if 0 <= new_prog <= 100:\n",
        "                selected[\"progress\"] = new_prog\n",
        "                if new_prog == 100:\n",
        "                    selected[\"status\"] = \"Completed\"\n",
        "                save_goals(goals)\n",
        "                print(\"✅ Progress updated successfully!\")\n",
        "            else:\n",
        "                print(\"⚠️ Invalid percentage. Enter a value from 0 to 100.\")\n",
        "        else:\n",
        "            print(\"⚠️ Goal ID not found.\")\n",
        "    except ValueError:\n",
        "        print(\"⚠️ Invalid input! Please enter numbers only.\")\n",
        "\n",
        "def view_analytics(goals):\n",
        "    \"\"\"Module 4: Generates summary statistics of tracked goals.\"\"\"\n",
        "    print(\"\\n--- GOAL ANALYTICS & SUMMARY ---\")\n",
        "    if not goals:\n",
        "        print(\"No goals to analyze. Add some goals first!\")\n",
        "        return\n",
        "\n",
        "    total_goals = len(goals)\n",
        "    completed = sum(1 for g in goals if g[\"status\"] == \"Completed\")\n",
        "    in_progress = total_goals - completed\n",
        "    total_progress = sum(g[\"progress\"] for g in goals)\n",
        "    avg_progress = total_progress / total_goals\n",
        "\n",
        "    print(f\"Total Goals Tracked : {total_goals}\")\n",
        "    print(f\"Completed Goals     : {completed}\")\n",
        "    print(f\"In-Progress Goals   : {in_progress}\")\n",
        "    print(f\"Average Completion  : {avg_progress:.1f}%\")\n",
        "\n",
        "def main():\n",
        "    goals = load_goals()\n",
        "\n",
        "    while True:\n",
        "        print(\"\\n==============================\")\n",
        "        print(\"   GOAL & HABIT TRACKER CLI   \")\n",
        "        print(\"==============================\")\n",
        "        print(\"1. Add New Goal\")\n",
        "        print(\"2. View All Goals\")\n",
        "        print(\"3. Update Goal Progress\")\n",
        "        print(\"4. View Progress Analytics\")\n",
        "        print(\"5. Exit\")\n",
        "\n",
        "        choice = input(\"Select an option (1-5): \").strip()\n",
        "\n",
        "        if choice == \"1\":\n",
        "            add_goal(goals)\n",
        "        elif choice == \"2\":\n",
        "            view_goals(goals)\n",
        "        elif choice == \"3\":\n",
        "            update_progress(goals)\n",
        "        elif choice == \"4\":\n",
        "            view_analytics(goals)\n",
        "        elif choice == \"5\":\n",
        "            print(\"Saving data and exiting... Goodbye!\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Invalid choice! Please select 1-5.\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}